version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default

    steps:
      - checkout
      - restore_cache:
          keys:
          - v0-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v0-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests pytest
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: Running tests unittests
          command: |
            . venv/bin/activate
            python3 -m unittest discover

workflows:
  main:
    jobs:
      - build-and-test
